name = input("Escreva seu nome: ")
age = input("Informe a sua idade: ")
profission = input("Informe a sua profissão: ")
cpf = input("Escreva seu C.P.F.: ")
email = input("Insira seu e-mail: ")
print("Olá " + name)
print("Sua idade é: " + age)
print("Sua profissão é: " + profission)
print("Seu C.P.F. é: " + cpf + ". Você não deveria passá-lo para alguém desconhecido")
print("Seu E-mail é: " + email + "               Entrarei em contato.")